[package]
name = "rustycable"
version = "0.1.0"
authors = ["Ieva Skrabutena <skrabutena.ieva@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.6.1"
tokio = { version = "0.2.18", features = ["full"] }
tonic = "0.2.0"
