name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Setup Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 5
    - name: Check formatting
      run: rustup component add rustfmt && cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install AnyT
      run: gem install anyt
    - name: Run AnyCable conformance tests
      run: anyt -c "./target/debug/rustycable" --target-url="ws://localhost:8081/cable"
